### ISSUE TITLE
How to prevent the creation of new PDFs in the user_path

### ISSUE THREAD

**Issue by BhoomikaMuralidhara** [h2oai/h2ogpt#1041]
Hello, Is there a way to prevent the creation of new PDFs in the user_path folder and continue to ingest PDFs as before without any disruptions? The pdf is split into single page pdf.

**Comment by pseudotensor** [comment]
Can you give more details?  I can't quite follow.

It's true that if you upload from UI then the uploaded file goes to user_path, else document viewing won't work later.  However, otherwise  nothing is added to that directory.

But I can't tell what you mean by "and continue to ingest PDFs as before without any disruptions?"  What disruption?

As for PDF split into multiple pages, this happens for DocTR model to avoid excessive memory usage, by doing each page, but those files do not stay in the user_path folder, they get deleted.

Perhaps the last is what you mean though, that temporarily they are there.  I can make them into temp.
