### ISSUE TITLE
Not showing any answer with Mistral model but still showing sources (RAG/Docker Setup)

### ISSUE THREAD

**Issue by dakotal4** [h2oai/h2ogpt#1101]
I am running on an H100 with a docker setup. I keep running into this issue when I use mistral 7b that an answer will not show up, but the sources will still show as if it knows I'm asking a question about my document. So I know the answer is generating, but I just don't see anything. I was doing some digging in the github and @pseudotensor recommended to use mistral 7b for rag and not llama 2 7b. I have this long, repetitive document that llama 2 7b can't decipher because I assume of it's limited context window. I have tried changing --max_seq_len to see if that was the problem, but I know I have enough vram to probably run it at the maximum sequence length. Any help would be appreciated. Added pictures of the background activity as well.
![Capture](https://github.com/h2oai/h2ogpt/assets/145373637/a60985e9-a2f5-48c9-8a2b-1151bb5945c2)
![Capture](https://github.com/h2oai/h2ogpt/assets/145373637/75847da2-5d4d-4fcf-9535-dfe938f2ed61)
![Capture](https://github.com/h2oai/h2ogpt/assets/145373637/186154a9-2a3c-4fc9-ba91-6912158a7321)

**Comment by Blacksuan19** [comment]
use latest docker image tag and set prompt mode to mistral instead of llama2

**Comment by dakotal4** [comment]
Switched prompt mode to mistral and still getting no output. And I updated my docker image last week is there a new one already?

**Comment by pseudotensor** [comment]
@dakotal4  You are using a foundational model rather than an instruct model, so the prompt is "plain" by default (i.e. no prompting).  If you really intend this, you can try using "one_shot" for prompt type, but I assume you are just making a mistake in using `mistralai/Mistral-7B-v0.1`.

I think you instead meant to use `mistralai/Mistral-7B-Instruct-v0.1` and we'll detect that name as "mistral" prompt_type or you can pass it.
