### ISSUE TITLE
help setting up custom prompt pls

### ISSUE THREAD

**Issue by fahadshery** [h2oai/h2ogpt#1106]
Hi,

I am looking at this [here](https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#adding-prompt-templates).
I have the following prompt:
```bash
## Task
Generate a SQL query to answer the following question:
`{prompt}`

### Database Schema
This query will run on a database whose schema is represented in this string:
CREATE TABLE products (
  product_id INTEGER PRIMARY KEY, -- Unique ID for each product
  name VARCHAR(50), -- Name of the product
  price DECIMAL(10,2), -- Price of each unit of the product
  quantity INTEGER  -- Current quantity in stock
);

CREATE TABLE sales (
  sale_id INTEGER PRIMARY KEY, -- Unique ID for each sale
  product_id INTEGER, -- ID of product sold
  customer_id INTEGER,  -- ID of customer who made purchase
  salesperson_id INTEGER, -- ID of salesperson who made the sale
  sale_date DATE, -- Date the sale occurred
  quantity INTEGER -- Quantity of product sold
);

-- sales.product_id can be joined with products.product_id

### SQL
Given the database schema, here is the SQL query that answers `{prompt}`:
```

What's the best way to set it up?
I believe it's going to be a custom prompt.
Any help would be appreciated

**Comment by pseudotensor** [comment]
Hi, I've been busy and I didn't fully understand the question, so I wasn't able to really contribute much.

My recommendation for getting the model to respond with SQL is to use a  model that's appropriate, i.e.

https://huggingface.co/BAAI/AquilaSQL-7B

see:

https://yale-lily.github.io/spider


Otherwise, in general, best to put such meta instructions into a system prompt.  E.g. see how h2oGPT does it for its JSON mode by choosing `--doc_json_mode=True` in CLI or selecting it in UI.

It uses this system prompt:

https://github.com/h2oai/h2ogpt/blob/4e1f55d15d1ffd3c441e58008e5b5323a477380a/src/enums.py#L363-L375

and then during Q/A it adds even more to ensure get JSON:

https://github.com/h2oai/h2ogpt/blob/4e1f55d15d1ffd3c441e58008e5b5323a477380a/src/gpt_langchain.py#L6172-L6180
