### ISSUE TITLE
TypeError: Audio.__init__() got an unexpected keyword argument 'show_recording_waveform'

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#1176]
I try to install latest  h2oGPT Client Nightly Release - 2023-12-04 using **README_LINUX.md**
 
And following all the instruction from creating new conda environment to end. when hiting `bash docs/linux_install.sh`  then some shows dependency conflicts happened but building the wheel.

But the main thing is that when i hitting the command ` python generate.py --base_model=meta-llama/Llama-2-13b-chat-hf  --score_model=None --langchain_mode='UserData' --user_path=user_path --use_auth_token=True --max_seq_len=4096 --max_max_new_tokens=2048
Using Model meta-llama/llama-2-13b-chat-hf` 

Then I get the error that attached in the below screenshot. I capture the whole window for better error reference.

![typeerror](https://github.com/h2oai/h2ogpt/assets/137979399/1968034b-9ea8-4156-919f-dd9d24bca461)

**Comment by pseudotensor** [comment]
You are using gradio 4 and need to go back to gradio 3.  We temporary switched to gradio 4 for a couple days until it was seen to be too unstable to use, so you probably pulled and installed deps at that time, but since today didn't change deps but updated code.

The placeholder for show_recording_waveform=True is only for gradio 4 which we do not support until they have fixed bugs.
