### ISSUE TITLE
Anyway to "contain" the installation?

### ISSUE THREAD

**Issue by ChiNoel-osu** [h2oai/h2ogpt#1238]
Just like the one-clicked installed version, I'm looking for a way to contain the manually installed h2oGPT, meaning that everything stays in that one folder.
As for now, user is required to install extra like MSVC and stuffs like that which remain absolutely useless (for most people) after the installation is complete. That clutters user's Windows installation. And from my experience, the VS installer typically does a poor job actually removing them completely.
I aimed to not installing anything extra other than `Python` and `git` in my system and use `python venv` instead of `conda`. But I guess that's not practical as we need to install the `cudatoolkit`.
Containing the installation helps a lot especially for folks who has a small system drive. And is generally a great idea in my opinion.

**Comment by pseudotensor** [comment]
I don't think anything prevents you (in manual case) from having everything in single folder.  Most things go to single folder already, except ~/.cache stuff like HF transformers models, but you can review their documentation to control that.

The main issue is /tmp/gradio uploads.  That's controlled by gradio itself and there's no option for it.  But if you set user_path, then for that shared or personal collection all temp files are copied to that folder, so again controlled.

But maybe explain what the issue is?  For windows, the one-click is only way I'm aware of to get all the other blobs to be isolated.  And I'm just using a package to do all that, I'm not expert in containing things in windows.

Feel free to mention more, but for now I assume windows kit I use is good enough, others have said is uninstalls well, and I've seen the same.

**Comment by ChiNoel-osu** [comment]
@pseudotensor Thank you for replying. Allow me to rephrase myself.
Maybe using the word "contain" is a bit misleading. I have no problem containing the files, models and stuff like pip packages. The issue is during the installation process, we need to install extra prerequisites into the system like gcc and MSVC and conda. But I guess it's inevitable due to how things work. However the one-click version is very well "contained".
I think people go for manual install to get newer code. So if we can get an update script or something in the one-click install version, that'd be pretty amazing.

**Comment by pseudotensor** [comment]
The new windows installer is easier to upgrade, since pip is included.  So most of the time one can just run through the manual installation process but as applied to the one-click installer python.exe
