### ISSUE TITLE
Model weights on VRAM  and Embeddings on RAM

### ISSUE THREAD

**Issue by Abdoulaye-Sayouti** [h2oai/h2ogpt#1245]
Hi, is it possible to have the model weights on VRAM (Video RAM, typically on the GPU) and the embeddings on RAM (the system's main memory) ?

**Comment by pseudotensor** [comment]
Use `--pre_load_embedding_model=True --embedding_gpu_id=cpu --cut_distance=10000 --hf_embedding_model=BAAI/bge-base-en-v1.5` on new main.

The first 2 are required, the other 2 are optional but recommended so the model is smaller.

Note, it takes about 0.3seconds per chunk on my i9 using instructor-large.  That's why you probably want to use a smaller bge model of much smaller size like above.

See https://huggingface.co/spaces/mteb/leaderboard for other options for smaller size that are still quite accurate, where smaller should be faster on CPU.
