### ISSUE TITLE
Understanding h2oGpt and inference server relationship

### ISSUE THREAD

**Issue by konradzuse** [h2oai/h2ogpt#1259]
I’m fairly new to ai and h2oGpt.

I’m struggling to understand how h2oGpt works together with an inference server such as vLLM. Do they share the same model, and can it be trained with user uploaded documents in the same way if using h2oGpt alone?

If I’m calling from python code, is it advised to use the gradio client, or go directly to the vLLM apis?

some explanation would be gratefully appreciated

**Comment by pseudotensor** [comment]
If one passes --inference_server, then h2oGPT no longer loads the model weights, only the config and tokenizer if using HF model, or fake tokenizer if using llama.cpp, etc.

h2oGPT with or without inference server acts like having the local torch one from an accuracy standpoint.  However, the major benefit of using (say) vLLM is it allows for concurrency built-in well, while torch with multi-threading is not possible due to the k-v cache used in LLMs that would mess-up if accessed by multiple threads.  Similar for TGI server, and of course for OpenAI, Anthropic, Google, etc.  llama.cpp is also the same, multi-threading is not possible as llama.cpp is not thread safe.

I recommend using the new OpenAI client if just using client to ask questions on fixed docs, e.g. https://github.com/h2oai/h2ogpt/issues/1217#issuecomment-1873009062

If you need to upload docs via client, then gradio_utils/grclient.py is good, or yes gradio_client for fine-trained access with many examples given in readme and esp tests.

**Comment by konradzuse** [comment]
Thanks for the response.

Can you explain how vLLM is able to access the content of the UserData collection? Is this something that vLLM loads with the model, or is it passed to vLLM with every request?

**Comment by pseudotensor** [comment]
@konradzuse I'll make tiny text picture, maybe helps.

Local model: User -> Gradio Client API or UI -> Gradio Server -> Torch model

Inference server: User -> Gradio Client API or UI -> Gradio Server -> vLLM/TGI/OpenAI/Google/Anthropic/etc. inference servers

One can also talk to h2oGPT as if it were OpenAI server, i.e.:

Local model: User -> OpenAI Python Client API -> OpenAI Proxy h2oGPT Server -> Gradio Server -> Torch model

Inference server: User -> OpenAI Python Client API or UI -> OpenAI Proxy h2oGPT Server -> Gradio Server -> vLLM/TGI/OpenAI/Google/Anthropic/etc. inference servers


Does that help?

The inference server just handles the pure LLM part, not the docQA part that h2oGPT handles.

**Comment by konradzuse** [comment]
Thanks again. This is helpful in understanding how the parts fit together.

How does the docQA part work if I've configured an inference server? Does it use vLLM at all, or handle that using Torch?

**Comment by pseudotensor** [comment]
If you use --inference_server torch for the LLM model weights is not used, just the network is used to talk to the inference server.

**Comment by konradzuse** [comment]
ok. Is concurrency still supported for docQA in that case?

**Comment by pseudotensor** [comment]
Ya, concurrency issue is only with the LLM part (i.e. torch for model weights), that vLLM etc. solve
