### ISSUE TITLE
Don't do reduction in summary when first run is already based on the whole text

### ISSUE THREAD

**Issue by wypiki** [h2oai/h2ogpt#1305]
Especially with Mixtral with its large context window, text for summary usually fits within the context window during the first run. A further reduction is unnessary and the first run usually gives a much better structured result. It's bad to see the perfect detailed summary disappear for a more reduced one.

**Comment by pseudotensor** [comment]
Yes, Dup of: https://github.com/h2oai/h2ogpt/issues/1298  Just posted 3 days ago.  It's easy to do.

Issue is that sometimes the first pass is too long, esp. from Mixtral, and reduction helps.  But some prompt engineering might help with that so single pass is ok.

Also, would be great if the other passes were visible.

But if you really just want a single  pass and know it, you can  use "extract" instead of summarize, and it'll do a a single "map" and no reduce.
