### ISSUE TITLE
First time use on windows throwing up odd missed path

### ISSUE THREAD

**Issue by Sierbahnn** [h2oai/h2ogpt#1355]
Hi
Very new here, terribly excited.

I am running a fresh install on Windows, and when I get to this part

GPU: Before starting, run the following commands (replace pseud with your user):

C:\Users\pseud\AppData\Local\Programs\h2oGPT\Python\python.exe -m pip uninstall -y torch

and I change the username to mine, I find that the path is not valid. 
In fact, my appdata\}ocal\ is missing the h2oGPT altogether. 
All of h2ogpt I have is a log from the install in the roaming-folder and a shortcut to the folder, also in roaming.
Did I make a mistake and if so, how do I correct it? Or is the installer missing a step somewhere?

Thanks.

**Comment by pseudotensor** [comment]
Hi that line depends upon where you installed h2oGPT when using the one-click installer.  I gave my line as example.

You can look at the properties of the h2oGPT icon and see where it points to launch h2oGPT and match that directory.

**Comment by Sierbahnn** [comment]
Great! Thank you. Now it is rocking. Hopefully that resolves some of the other issues I have been having. :)

**Comment by pseudotensor** [comment]
Can you report what the path ultimately was?  I can add another example in the readme.md part.

**Comment by Sierbahnn** [comment]
D:\Program Files (x86)\h2oGPT\Python>Python\python.exe

It is downloading now, and we'll see if this resolves the speed-issue and the other issue I brought up on Discord. This is all very new to me, so there is a lot I do not know yet.

**Comment by Sierbahnn** [comment]
Right, progress, but with a warning

![image](https://github.com/h2oai/h2ogpt/assets/68108749/2b1960fd-95d5-4262-861c-e7a58fd193d0)

This seems straight forward enough, but I have no idea how to add it to the path. What does that mean? I am guessing it is a common thing for a non-windows user, but I am floundering here.

**Comment by pseudotensor** [comment]
Not seen before, but guess it's ignorable since we don't use caffe2 in h2oGPT.

**Comment by Sierbahnn** [comment]
I found a way to add the path to the environment variables in the windows settings, just in case.

**Comment by pseudotensor** [comment]
Maybe there is old h2oGPT still active and things are getting mixed up.  Can you check ctr-alt-del for other Python processes?

**Comment by Sierbahnn** [comment]
After rebooting the machine I started afresh and still no models


![image](https://github.com/h2oai/h2ogpt/assets/68108749/6092145d-1aaf-4d8e-b734-0aa7332659cc)

What am I missing here? Is there a step I missed? I did perform the entire installation, as far as was documented.

**Comment by pseudotensor** [comment]
Hi, maybe it's about expectations, I'm not sure.  What do you want to see or happen?

**Comment by Sierbahnn** [comment]
And I have to download a model each time I run the application? There is no way for me to see which models have been downloaded and are available to me somewhere?
Is it not possible to have one model load in as the application starts so I can start my chat without going into another tab to select and potentially have to download a model to start chatting?

**Comment by pseudotensor** [comment]
No you don't have to re-download the model every time.

When you download a model and it sits in the llamacpp_path, it appears in the UI automatically.   If downloaded from UI, it automatically fills that path and appears in the list.

Every time you start h2oGPT with its UI, that model list in the UI is populated from what is on the disk.

If you want to start chatting for arbitrary number of models (loading and unloading several mdoels) you need to avoid --base_model at CLI time and go to models tab and select it.

--base_model is way for the model to appear for all users (API and multi-user UI access in mind), which is what h2oGPT has focused on.  If you use --base_model, you get that model during start.

If you want to switch models, due to how gradio works, there's no current way to use --base_model and then switch in memory efficient way to a new model in models tab.  But it's not alot of work to go to models tab and click whichever model you want.

Switching models for multi-user makes no sense if loading models into GPU memory, so why it hasn't been focus since h2oGPT focuses on high concurrency multi-user UI and API access.

But there may be hacks to make it work for single user.

**Comment by pseudotensor** [comment]
Closing, but I think maybe UX issue with h2oGPT, user doesn't know that they should enter a model HF link etc. into the "Choose/Enter" drop down text or something.
