### ISSUE TITLE
keeps repeating Donald Trump quotes at me

### ISSUE THREAD

**Issue by G-force78** [h2oai/h2ogpt#165]
Firstly thank you this is very neat , simple to start and slick to use.

Heres the issue, I started langchain ```
pip install -r requirements_optional_langchain.txt
python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6.9b  --load_8bit=True --langchain_mode=UserData --user_path=user_path
```
Uploaded a text file in the UI and selected user data and add file to shared userdata. When adding a jpg it did a good job of describing it but then realed off some Trump quotes. I cant even get it ti answer anything from txt files it just returns unrelated paragraphs, then some Trump lol

**Comment by pseudotensor** [comment]
Hi, sorry about that.  A collaborator removed 6.9 from the prompt type list and it was no longer using the correct prompt.  I just merged a fix.

i.e. issue was `h2oai/h2ogpt-oig-oasst1-512-6.9b` was not using any prompting anymore, just "plain" because it was removed after name change to `h2oai/h2ogpt-oig-oasst1-512-6_9b` -- i.e. . -> _.

But he didn't change the rest of the code to match.
