### ISSUE TITLE
How to make the summary of a text?

### ISSUE THREAD

**Issue by lelapin123** [h2oai/h2ogpt#176]
Can someone provide me a step by step set of instructions (post installation) to use the software to make the summary of a text that is in a .txt file ? Everything that i try and that looks intuitive doesn't work

**Comment by pseudotensor** [comment]
Great question.  I haven't yet added an explicit summarization button, but will soon.

The vector db itself isn't really good for summarizing.  If there happened to be an abstract or summary or conclusion in the text file, it might work to ask things like "Summarize the book the Great Gatsby".  However, if you use the actual book itself and try that, the LLM knows more and does a better job by itself than the vector database providing a few chunks of random text -- since the book doesn't itself have a summary.

I'd wait for any additional features before trying to summarize a text, unless it has summarization/abstract/conclusion like text in it.

**Comment by pseudotensor** [comment]
But I did find a bug, so thank you.  I'll add some tests so no regressions occur.

Works better now:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/f41b7fad-b258-429b-818c-6ae353cdb076)

**Comment by lelapin123** [comment]
So what settings (and databases) should you use to ask questions about a text?

**Comment by pseudotensor** [comment]
Summary button is now in.
