### ISSUE TITLE
How much GPU memory should be used with vicuna13b and langchain to get answers from docs

### ISSUE THREAD

**Issue by qmzpg** [h2oai/h2ogpt#198]
I write a program using vicuna13b and langchain to get answers from documents ,  but the program report "GPU out of memory". Need 46GB.

**Comment by lelapin123** [comment]
are you in 4 bits or 8 bits.
I tried this model and i think that i was able to run it in 8 bits, but once i wanted to use some 4 bits models, i had the same problem as you. (this is not a definitive explanation).

**Comment by pseudotensor** [comment]
I have 24GB and can run vicuna13b just fine. It's basically same size as 12b h2ogpt model that also fits fine:

```
python generate.py --base_model=junelee/wizard-vicuna-13b --load_8bit=True --h2ocolors=False
```

But you have to have about 32GB free just to handle the CPU size of loading that model for each shard to get onto GPU.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/926ffeba-ad0a-421e-97de-14c97cf4d4d0)

![image](https://github.com/h2oai/h2ogpt/assets/2249614/300ddf75-976f-4e5b-90ee-3b29198faff6)


Of course, when the input is large, like when doing langchain, 8-bit is slower than 16-bit.

Also, I need to fix this: https://github.com/h2oai/h2ogpt/issues/192 .  Currently, the prompts use to control the model can get truncated when many docs passed.  Then the generation can continue because it does:
```
# truncated with no <human>:
<bot>: Answer
```
And so it wants to repeat again <bot>:.
