### ISSUE TITLE
validate huge files last

### ISSUE THREAD

**Issue by chris-aeviator** [h2oai/h2ogpt#226]
When interacting with h2ogpt I regularly run into a situation where the base model is loaded just to realize a validation fails, e.g. local_files_only but missing a tokenizer, wrong folder for resume_from_checkpoint etc.

Everytime the base model loads it takes an considerable amount of time, just to fail fast after.

I propose to validate the smaller models first before loading the base model

**Comment by pseudotensor** [comment]
It's certainly true that testing a setup on smaller model is good.  E.g. we often will do the following just to ensure code is working, etc.:

1) Use distilgpt2 as base model or if doing 8-bit or 4-bit etc., then use 6_9 model
2) Use epoch=0.001

Then one checks that things complete etc.  Bugs in peft mean one has to copy checkpoint pytorch bin file over to adapter model bin at end that is empty-ish.

Does this workflow make sense to you?

We could probably move the model loading to just before the Trainer() is called, but otherwise we cannot move it any more since that is just a HF class we use.  So, we have Trainer() validate the checkpoint before model is loaded.

We could add some checks that trainer does perhaps, if that's what you are thinking.

**Comment by chris-aeviator** [comment]
Good idea with the workflow. Maybe a sanity check for the folders and .bin files being present?

**Comment by pseudotensor** [comment]
too complex in general
