### ISSUE TITLE
How i dupe this version?

### ISSUE THREAD

**Issue by Toaster496** [h2oai/h2ogpt#311]
how do i dupe this https://gpt-gm.h2o.ai/ not https://gpt.h2o.ai/

**Comment by pseudotensor** [comment]
https://gpt-gm.h2o.ai/ just uses https://github.com/huggingface/chat-ui like HF Chat uses, and connects to an endpoint using https://github.com/huggingface/text-generation-inference with this model chosen: https://huggingface.co/h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v2

Chat-UI is definitely cleaner than standard gradio.  However, chat-ui is hard to develop for most since not python based.

But I'll be doing my best to make the gradio stuff look better, along lines of https://raw.githubusercontent.com/sunner/ChatALL/main/screenshots/screenshot-1.png or https://github.com/oobabooga/text-generation-webui
