### ISSUE TITLE
error in downloading model

### ISSUE THREAD

**Issue by Aashna2022** [h2oai/h2ogpt#336]
I am using h2oai/h2ogpt-oig-oasst1-512-6_9b this model but its not working locally . what should I do to use gpt4all model . And also where I should locate the model.

**Comment by pseudotensor** [comment]
For CPU, I recommend the llama model mentioned in the readme, rather than the gpt4all models.  The llama model is downloaded from the link in the readme for the 7b or 13b models.

==============

So, for chatting, a better instruct fine-tuned LLaMa-based model for llama.cpp can be downloaded from [TheBloke](https://huggingface.co/TheBloke).  For example, [13B WizardLM Quantized](https://huggingface.co/TheBloke/wizardLM-13B-1.0-GGML) or [7B WizardLM Quantized](https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML).  TheBloke has a variety of model types, quantization bit depths, and memory consumption.  Choose what is best for your system's specs.  However, be aware that LLaMa-based models are not [commercially viable](docs/FAQ.md#commercial-viability).

For 7B case, download [WizardLM-7B-uncensored.ggmlv3.q8_0.bin](https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML/blob/main/WizardLM-7B-uncensored.ggmlv3.q8_0.bin) into local path.  Then one sets `model_path_llama` in `.env_gpt4all`, which is currently the default.

**Comment by auwsom** [comment]
just fyi for readers, the "commcially viable" link changed to https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#commercial-viability.. basically the LLaMa model is owned by facebook, while others are open source.
