### ISSUE TITLE
About UserData and MyData

### ISSUE THREAD

**Issue by joaonevesvisualnuts** [h2oai/h2ogpt#369]
When I upload anything to these databases, are they public?
From what I understood, "MyData" is for me only, "UserData" is shared, but shared with whom?
Is it with everyone connected to my private server or is it to a public server?

Thank you in advance.

**Comment by pseudotensor** [comment]
UserData: Shared with anyone who is on your server.  Persisted across sessions in single location for entire server.  Control upload via allow_upload_to_user_data option.  Useful for collaboration.

MyData: Scratch space that is inaccessible if one goes into a new browser session.  Useful for public demonstrations so that every instance is independent.

**Comment by intelligenceabhii** [comment]
It has been observed that when accessed without authentication, the MyData PDF is deleted as expected. However,  the MyData collection is not deleted upon page load / re-load on the Document tab when accessed with authentication. How to achieve the docs deletion with authentication? Please help!!!
