### ISSUE TITLE
Customized Prompts

### ISSUE THREAD

**Issue by Haxeebraja** [h2oai/h2ogpt#390]
I want to set customized prompt for chat responses. What is the method to set it?

Moreover, is there any documentation for the following prompts in finetune.py:
    plain = 0
    instruct = 1
    quality = 2
    human_bot = 3
    dai_faq = 4
    summarize = 5
    simple_instruct = 6
    instruct_vicuna = 7
    instruct_with_end = 8
    human_bot_orig = 9
    prompt_answer = 10

**Comment by pseudotensor** [comment]
Yes you can use "custom" and choose arbitrary "prompt_dict" in UI or in CLI.

**Comment by Haxeebraja** [comment]
> Yes you can use "custom" and choose arbitrary "prompt_dict" in UI or in CLI.

@pseudotensor  Can you share an example of passing custom prompt to UI?

**Comment by pseudotensor** [comment]
Ok.  baseline:

```
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --save_dir=save_7b --max_max_new_tokens=2048 --max_new_tokens=1024 --langchain_mode=MyData
```

gives:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/a6cb91fe-022d-45e9-8fad-48c9adabd184)


In UI there is this in `Models` tab, since prompt_dict should be chosen for each model ideally:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/b37e1dae-e1e4-4a80-bb59-c0d0395105ea)


If I change prompt_type to custom in expert and then change this so looks "plain" then I can mimic "plain" prompt_type:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/ccedd2d5-b500-458d-80eb-8f27b54003db)

and change:
```
{'promptA': '', 'promptB': '', 'PreInstruct': '<|prompt|>', 'PreInput': None, 'PreResponse': '<|answer|>', 'terminate_response': ['<|prompt|>', '<|answer|>', '<|endoftext|>'], 'chat_sep': '', 'chat_turn_sep': '<|endoftext|>', 'humanstr': '<|prompt|>', 'botstr': '<|answer|>', 'generates_leading_space': False}
```
to the prompt_dict shown which switched to "plain" (i.e. copy-paste from UI):
```
{'promptA': None, 'promptB': None, 'PreInstruct': None, 'PreInput': None, 'PreResponse': None, 'terminate_response': [], 'chat_sep': '', 'chat_turn_sep': '', 'humanstr': None, 'botstr': None, 'generates_leading_space': False}
```

you'll get now:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/07d34903-a29d-4c13-ac51-a0829b480e74)
