### ISSUE TITLE
Can h2ogpt chatbox retain the context of previous questions?

### ISSUE THREAD

**Issue by liamnguyen97** [h2oai/h2ogpt#446]

**Comment by pseudotensor** [comment]
The chat context is always included when talking to LLM.  If it gets too long, the oldest stuff gets cut truncated.

If a collection is selected, only the document context + query is provided, because nominally the context is too small to handle the chat context + document context + query.

Also, most LLMs start to get quite confused if so much extended mixed types of information is in the context.

I can add some options, but it's easy to ask LLM with all context by switching to ChatLLM "collection"
