### ISSUE TITLE
FR: how to add new file types to analyze?

### ISSUE THREAD

**Issue by wizzard0** [h2oai/h2ogpt#466]
I've found the Language enum but can't find the place where the files are filtered in the first place.

I want to try indexing code in different languages and also to prepend the file type/name to the extracted text (eg "React component: SuperButton.tsx")

But at least where to add extensions so they would be indexed as plain text)

Because there's Language.JS but the .js files don't get added

**Comment by pseudotensor** [comment]
Hi, `file_to_doc` function controls the ingestion.  These files are allowed ones: https://github.com/h2oai/h2ogpt/blob/1184f057088743599e2d5241329551b8f7f5320d/src/gpt_langchain.py#L1021-L1035

If one wants to add a new file type,   just add it to the list `file_types` and then add an entry in `file_to_doc`.

I didn't take PrivateGPT approach of making an enum for type -> function, because in some cases it's more complex and multiple methods are tried or there are various conditions.
