### ISSUE TITLE
q: how to view sources from the db included in the prompt when using llama/ggml models?

### ISSUE THREAD

**Issue by wizzard0** [h2oai/h2ogpt#473]
i've added the `print(prompt)` in gen.py:1583 but it seems to fire only on some models (eg the default one), but not on llama ones in particular

**Comment by pseudotensor** [comment]
run_qa_db() is a code path required for llama/gpt4all models because I use langchain LLM classes to manage those, even though I edited those classes alot.  The rest I have my own code that doesn't need langchain, and if no documents are queried, then run_qa_db() isn't used.

But if you are curious about sources, in UI you can click on "RelSources" or "TopKSources" and click submit for a given collection and get sources for a particular query or unrelated to any query.

Perhaps you mean the CLI, and right now no way to get sources.  I'm happy if someone develops the CLI more, but the UI is my main focus for advancements.
