### ISSUE TITLE
Does this model only work serially?

### ISSUE THREAD

**Issue by fk0000** [h2oai/h2ogpt#617]
I open multiple websites of this model that I deployed myself, and submit the work separately, but they can't work in parallel, they can only be put into the queue for serial processing

**Comment by pseudotensor** [comment]
```
--concurrency_count=4
```
or choose whatever you like.  However, this uses a shared model state, and not all models will handle that well due to caching in the model.  E.g. falcon has issues, so we disable caching.

For optimal concurrency best to use vLLM or TGI inference servers.  There's no real cost and relatively easy to setup.
