### ISSUE TITLE
Parameter local_files_only not working

### ISSUE THREAD

**Issue by dlippold** [h2oai/h2ogpt#797]
When I execute
`python generate.py --score_model=None --share=False --local_files_only=True --base_model='llama' `
I get the following output:

> Auto set langchain_mode=LLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path or langchain_mode_paths, and ensure allow_upload_to_user_data=True
> No GPUs detected
> Using Model llama
> Prep: persist_directory=db_dir_UserData exists, using
> Starting get_model: llama 
> /home/h2ouser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:995: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
>   warnings.warn(
> Could not determine --max_seq_len, setting to 2048.  Pass if not correct
> BEGIN get url https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q8_0.bin

Although I use `--local_files_only=True` a file of several GB (llama-2-7b-chat.ggmlv3.q8_0.bin) is downloaded.
Instead h2oGPT shout output an error message that no model is available.

If you think the current behavior is correct and the meaning of `--local_files_only` is different from what I expect please add an option to disable **all** downloads (so that it simulates a offline mode).

**Comment by ryanchesler** [comment]
In order to make that work you will need to point to a model that has already been downloaded and point --base_model to the path. 

For example here is what mine looks like:

`python generate.py --base_model='/home/ryanc/.cache/huggingface/hub/models--h2oai--h2ogpt-4096-llama2-13b-chat/snapshots/4a1968218a334323d847ed2fcf6cb661b74b5e68/' --prompt_type=llama2 --local_files_only=True`

Pointing to the cache directory where something was previously downloaded or wherever you have placed the files should work. Right now setting `--base_model='llama'` it doesnt have a local file to point to so it goes to huggingface. We could maybe improve this behavior by looking in the default cache directory or throwing an error instead of trying to download anyway.

**Comment by dlippold** [comment]
Thanks for the description how to use `generate.py` with a local model directory. But what I wanted to say is: The parameter `local_files_only` is not working in all situations, in particular it is not working in the described situation (no matter if the command was right or wrong), From my understanding of `--local_files_only=True` no download should happen but a download did happen.

**Comment by pseudotensor** [comment]
For general offline, see updates here: https://github.com/h2oai/h2ogpt/blob/main/docs/README_offline.md from https://github.com/h2oai/h2ogpt/pull/877
