### ISSUE TITLE
Apple Silicon Macs Benchmarks + Performance

### ISSUE THREAD

**Issue by kevinschaich** [h2oai/h2ogpt#881]
Could anyone that's successfully gotten a LLaMA2 model working with [MPS/GPU inference on an M1/M2 Apple Silicon Mac](https://github.com/h2oai/h2ogpt/blob/main/docs/README_MACOS.md) provide some details on the performance they've been seeing? E.g.:

* Which Mac & CPU/GPU are you running?
* Which models/size are you running? 
* How many tokens/sec are you getting?

The [benchmarks](https://github.com/h2oai/h2ogpt/blob/main/benchmarks/perf.md) page is very useful but I'm not sure if it's reasonable to expect to match even the bottom-end of Nvidia cards with a small model.

A chip like the M2 Max has a 38‑core GPU w/ up to 96GB unified memory; theoretically that memory should be usable by the GPU – so it should put it in the same ballpark as some of these Nvidia cards, but as I understand given the limitations of MPS the models have to be run as 4-bits. 

Curious to hear what others have been able to achieve.

**Comment by vesper8** [comment]
Would love some clarification on this as well. My maxed out M1 Max is performing very very slowly with the h2ogpt-gm-oasst1-en-2048-open-llama-7b model and I'm struggling to understand if it's something I'm doing wrong on my end.

**Comment by vesper8** [comment]
For comparison I just got `llama-2-7b-chat.ggmlv3.q4_0.bin` and ran it with `python3 generate.py -base_model=llama --model_path_llama=llama-2-7b-chat.ggmlv3.q4_0.bin --max_seq_len=4096 --prompt_type=llama2` and it's 100x faster.. it's super fast

**Comment by Mathanraj-Sharma** [comment]
@vesper8 may I know how you are benchmarking across different models? Are you using any tool / library?

**Comment by vesper8** [comment]
@Mathanraj-Sharma I wouldn't say that i was benchmarking anything.. just eyeballing it. I guess what happened is that the `h2ogpt-gm-oasst1-en-2048-open-llama-7b` model was not a GGML model nor a quaint.. it was the full model or something.. and that's why it was so slow. I have since learned that I need to use quaints only with my Mac.. q4 or q5_k_m or q6_k, I've been doing that and it's running much much faster now.

To be honest I have also already moved on to LM Studio.. it's just so easy to use in comparison and just works great.

**Comment by pseudotensor** [comment]
@Mathanraj-Sharma Please take a look at LM Studio again and see what we need to improve UX.  E.g. maybe should be easier to load model and be clear whether quantized recommended.  And UI improvements.  Thanks!

**Comment by vesper8** [comment]
@pseudotensor I'm going to assume you meant to tag me, and not Mathan.. since I'm the one who mentioned LM Studio.

I'll give you a few reasons why I prefer LM Studio (LMS).

1-LMS is obviously much much easier to install as it is a standalone app.. so no need to install any dependencies or python env
2-LMS works with GGUF which appears to be the new standard, it seems that for now h2ogpt only works with GGML. It also wasn't clear which quants it supports, I read in the issues that it only supported q4's, but I found out that LMS supports several more, q5_k_m and q6_k. I ended up getting a bunch of GGUF q6_k models from TheBloke
3-Having to know (and understand) beforehand which promptType to add to the command line parameters is confusing for a newcomer.
4-This may already be possible, but ideally I'd like to specify to h2ogpt a folder containing all my models (and it should be able to look for models in subfolders recursively) and not have to specify a single model when running the python command, and then I would be able to pick which model to use via a dropdown. LMS allows for exactly this and I find it very convenient.
5-I found that when using h2ogpt, I could ask a question of a model, and then a follow-up question, and it wouldn't have memory of my first question. But with LMS this works out of the box. I'm sure there's a way to enable memory in h2ogpt but maybe this should be on by default.

Best is to just use LMS and see for yourself where you can improve h2ogpt. Of course there's also oobabooga/text-generation-webui which has a lot of traction and will be familiar to anyone used to using AUTOMATIC1111/stable-diffusion-webui

Hope that helps! Cheers!

**Comment by Mathanraj-Sharma** [comment]
@vesper8 thanks for your valuable input, we are planning to improve, and I’ll keep a tab on your inputs.

btw AFAIK for (2), the limitation on q4 is only for llama models if you are running it on Mac MPS (M1/M2) GPU Mode. Otherwise, you can run it with other quantizations as well

LLama `q8` works for me on Mac M1 in CPU Mode
```bash
python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path --model_path_llama=https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q8_0.bin --max_seq_len=4096 --llamacpp_dict="{'n_gpu_layers':0,'n_batch':128}"
```
![image](https://github.com/h2oai/h2ogpt/assets/30664910/18c3d0fd-2955-4159-bdfb-62656d015f77)


@pseudotensor could you please confirm it for Ubuntu & Mac Intel?

**Comment by dingzhongshan** [comment]
@Mathanraj-Sharma thanks for pasting the m1 suggestion. Apologies if this is hi-jacking the thread but do you have anything for an M2 along the lines of that benchmark/orig issue? I get the following on the latest build (10-24-2023) from main (conda rust, per MAC FAQ).  btw, I will submit a bug/issue in sep-thread if needed. 

`File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for H2OLlamaCpp
__root__
  Could not load Llama model from path: llama-2-7b-chat.ggmlv3.q8_0.bin. Received error  (type=value_error)
`

Thanks (ding)

**Comment by pseudotensor** [comment]
@dingzhongshan Likely the file is not present where expected.  Did you download it? You can pass a URL from huggingface instead if that helps, when choosing --model_path_llama

e.g.
```
python generate.py --base_model=llama --model_path_llama=https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q8_0.bin --max_seq_len=4096
```

**Comment by Mathanraj-Sharma** [comment]
@dingzhongshan probably for your issue what @pseudotensor  mentioned above is the cause. 

But one other thing to note is that you should only use `q4` llama models when running on Mac M1/M2, because `llama-cpp-python` currently only supports `q4` for MPS

**Comment by dingzhongshan** [comment]
Hi @pseudotensor @Mathanraj-Sharma I followed the instructions and still get the same "Could not load Llama model from path" error. I did confirm the model was downloaded from huggingface. My user does have perms to the file. I also downloaded the file directly using git-lfs and pointed to the file. Same error. Lmk if you would like a separate issue opened for gpt4all_llm.py (or related). (ding)

`python generate.py --base_model=llama --model_path_llama=https://huggingface.co/TheBloke/Llama-2-7B-GGML/resolve/main/llama-2-7b.ggmlv3.q4_0.bin --max_seq_len=4096
Using Model llama

BEGIN get url https://huggingface.co/TheBloke/Llama-2-7B-GGML/resolve/main/llama-2-7b.ggmlv3.q4_0.bin
GOT url https://huggingface.co/TheBloke/Llama-2-7B-GGML/resolve/main/llama-2-7b.ggmlv3.q4_0.bin
DONE url https://huggingface.co/TheBloke/Llama-2-7B-GGML/resolve/main/llama-2-7b.ggmlv3.q4_0.bin
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from llama-2-7b.ggmlv3.q4_0.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/Users/Downloads/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "/Users/Downloads/h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/Users/Downloads/h2ogpt/src/utils.py", line 64, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/Users/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/Downloads/h2ogpt/src/gen.py", line 1306, in main
    model0, tokenizer0, device = get_model(reward_type=False,
  File "/Users/Downloads/h2ogpt/src/gen.py", line 1838, in get_model
    model, tokenizer, device = get_model_tokenizer_gpt4all(base_model, n_jobs=n_jobs,
  File "/Users/Downloads/h2ogpt/src/gpt4all_llm.py", line 16, in get_model_tokenizer_gpt4all
    model = get_llm_gpt4all(model_name, model=None,
  File "/Users/Downloads/h2ogpt/src/gpt4all_llm.py", line 161, in get_llm_gpt4all
    llm = cls(**model_kwargs)
  File "/Users/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for H2OLlamaCpp
__root__
  Could not load Llama model from path: llama-2-7b.ggmlv3.q4_0.bin. Received error  (type=value_error)`

**Comment by pseudotensor** [comment]
Ya if you have GGUF installed you cannot use GGMLv3.

FYI I updated main so that we focus on GGUF.  GGMLv3 support is not going to be maintained anymore as very old and llama.cpp project moved on from it long ago too.
