### ISSUE TITLE
request: parse files inside tar.gz archives

### ISSUE THREAD

**Issue by dkuku** [h2oai/h2ogpt#912]
That's the standard unix archive format, sometimes uses tgz extension but tar can be used with other compression formats for ex tar.xz

**Comment by pseudotensor** [comment]
It's relatively easy to do.  Will consider.

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor I can take a look at this. Could you please give me more context?

**Comment by pseudotensor** [comment]
@Mathanraj-Sharma Sure, zip and gz/gzip are handled here: https://github.com/h2oai/h2ogpt/blob/9629901696f5d61c21ea92d45fa75638c0fc5817/src/gpt_langchain.py#L2298-L2346

.tar.gz or .tgz would be most similar to .zip, just use same package used for gzip to ungzip and then unpack the tar using some other package into a folder like the zip case.  Then otherwise very much like the .zip case where it recurses on the path created.
