### ISSUE TITLE
Uploading a pdf from the UI results in the error "ValueError: xyz.pdf had no valid text and no meta data was parsed: None"

### ISSUE THREAD

**Issue by expectopatronm** [h2oai/h2ogpt#987]
Using the latest master branch, Python 3.8 venv.

I followed the stated instructions for requirements installation and repo set up, got the gradio server up and running and when I try to upload a PDF, it results in this error. 
I have verified the pdf is healthy and not corrupted.

**Comment by gabriead** [comment]
I am getting now this error when I try to upload a PDF: File ..........pdf exception: 'charmap' codec can't decode byte 0x8f in position 158192: character maps to <undefined>. The PDF is healthy and not corrupted

**Comment by pseudotensor** [comment]
Hi, nothing has changed w.r.t. the options, and I'm not seeing any new issues in tests or manual checks.

If you guys can find a particular PDF that fails that can be publicly shared, I'm happy to take a look.

**Comment by a3nima** [comment]
I wonder if images /graphics inside pdfs will be recognized and analysed/understood as well, it seems not by default?

**Comment by pseudotensor** [comment]
DocTR handles images in PDFs, since it just makes images of PDFs before doing OCR, and it's much better than tesseract.   However, nominally that is expensive, so the default of "auto" option for `enable_pdf_doctr` is only used for PDFs if pymupdf failed or there are < 100 pages.  One has to set it to "on" to always be used from CLI, or from UI choose to force it on.

I added some notes in the FAQ.  The stronger use of DocTR was only done last week.

**Comment by pseudotensor** [comment]
3318b1d65f93eeb731d3d73a63f5065a42260f0a
